language: c
sudo: true
matrix:
  include:
  - os: linux
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode6.4

install:
  - sh ./install-nix.sh

script:
- source ~/.nix-profile/etc/profile.d/nix.sh
- nix-env --version
- nix-env -i xz
- nix-env -i git
- git --version
- which git
- git clone https://github.com/NixOS/nix nix2
