language: c
sudo: true
matrix:
  include:
  - os: linux
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode6.4

install:
  - sh ./install-nix.sh

script:
- nix-env --version
- nix-env -i xz
- mkdir -p foo/boo
- touch foo/bar
- nix-env -i git
- git clone https://github.com/NixOS/nix nix2
